"""Tests for the protobuf wire-format reader.

The wire format is the one part of SCIP handling that can be tested to
certainty, because it is frozen and fully specified. Fixtures are built from
hand-written bytes rather than generated by a library, so a passing test
means the decoder agrees with the specification and not merely with itself.
"""

from __future__ import annotations

import pytest

from repoatlas.oracle import protobuf as pb


class TestVarint:
    @pytest.mark.parametrize(
        ("encoded", "expected"),
        [
            (b"\x00", 0),
            (b"\x01", 1),
            (b"\x7f", 127),
            (b"\x80\x01", 128),
            (b"\xac\x02", 300),
            (b"\xff\xff\xff\xff\x0f", 4294967295),
        ],
    )
    def test_reads_known_encodings(self, encoded: bytes, expected: int) -> None:
        value, position = pb.read_varint(encoded, 0)
        assert value == expected
        assert position == len(encoded)

    @pytest.mark.parametrize("value", [0, 1, 127, 128, 300, 2**31, 2**63 - 1])
    def test_round_trips(self, value: int) -> None:
        assert pb.read_varint(pb.encode_varint(value), 0)[0] == value

    def test_rejects_truncated_input(self) -> None:
        with pytest.raises(pb.ProtobufError, match="truncated varint"):
            pb.read_varint(b"\x80\x80", 0)

    def test_rejects_oversized_varint(self) -> None:
        with pytest.raises(pb.ProtobufError, match="exceeds 64 bits"):
            pb.read_varint(b"\x80" * 11 + b"\x01", 0)


class TestDecodeMessage:
    def test_decodes_a_hand_built_message(self) -> None:
        # Field 1, varint 150; field 2, string "hi".
        raw = b"\x08\x96\x01" + b"\x12\x02hi"
        fields = pb.decode_message(raw)
        assert pb.as_int(fields, 1) == 150
        assert pb.as_str(fields, 2) == "hi"

    def test_keeps_repeated_fields_in_order(self) -> None:
        raw = pb.encode_field(3, "a") + pb.encode_field(3, "b") + pb.encode_field(3, "c")
        assert pb.strings(pb.decode_message(raw), 3) == ["a", "b", "c"]

    def test_reads_packed_and_unpacked_repeated_ints_alike(self) -> None:
        packed = pb.encode_packed(1, [1, 2, 3])
        unpacked = b"".join(pb.encode_field(1, v) for v in (1, 2, 3))
        assert pb.int_array(pb.decode_message(packed), 1) == [1, 2, 3]
        assert pb.int_array(pb.decode_message(unpacked), 1) == [1, 2, 3]

    def test_decodes_nested_messages(self) -> None:
        inner = pb.encode_message([(1, "leaf"), (2, 7)])
        outer = pb.encode_field(5, inner)
        nested = list(pb.submessages(pb.decode_message(outer), 5))
        assert len(nested) == 1
        assert pb.as_str(nested[0], 1) == "leaf"
        assert pb.as_int(nested[0], 2) == 7

    def test_skips_unknown_fields_without_failing(self) -> None:
        known = pb.encode_field(1, "keep")
        unknown_varint = pb.encode_field(99, 42)
        unknown_fixed64 = b"\x81\x06" + b"\x00" * 8  # field 100, wire type 1
        unknown_fixed32 = b"\xad\x06" + b"\x00" * 4  # field 101, wire type 5
        fields = pb.decode_message(
            known + unknown_varint + unknown_fixed64 + unknown_fixed32
        )
        assert pb.as_str(fields, 1) == "keep"
        assert pb.as_int(fields, 99) == 42

    def test_rejects_group_wire_types(self) -> None:
        with pytest.raises(pb.ProtobufError, match="group wire type"):
            pb.decode_message(b"\x0b")  # field 1, wire type 3

    def test_rejects_field_number_zero(self) -> None:
        with pytest.raises(pb.ProtobufError, match="field number 0"):
            pb.decode_message(b"\x00\x01")

    def test_rejects_length_that_overruns_the_buffer(self) -> None:
        with pytest.raises(pb.ProtobufError, match="claims 10 bytes"):
            pb.decode_message(b"\x0a\x0aabc")

    def test_rejects_invalid_utf8_in_strings(self) -> None:
        raw = b"\x0a\x02\xff\xfe"
        with pytest.raises(pb.ProtobufError, match="not valid UTF-8"):
            pb.as_str(pb.decode_message(raw), 1)


class TestAccessors:
    def test_scalar_accessors_return_defaults_when_absent(self) -> None:
        fields = pb.decode_message(b"")
        assert pb.as_int(fields, 1, default=-1) == -1
        assert pb.as_str(fields, 2, default="none") == "none"
        assert pb.as_bytes(fields, 3, default=b"x") == b"x"

    def test_last_value_wins_for_scalar_fields(self) -> None:
        # Protobuf specifies that a repeated scalar collapses to the last one.
        raw = pb.encode_field(1, 1) + pb.encode_field(1, 2)
        assert pb.as_int(pb.decode_message(raw), 1) == 2

    def test_type_mismatch_is_reported(self) -> None:
        raw = pb.encode_field(1, 5)
        with pytest.raises(pb.ProtobufError, match="not length-delimited"):
            pb.as_str(pb.decode_message(raw), 1)

    def test_encoder_rejects_bools_to_keep_wire_type_explicit(self) -> None:
        with pytest.raises(TypeError, match="explicit"):
            pb.encode_field(1, True)  # type: ignore[arg-type]
